// <auto-generated />
using System;
using DoskarBakalare.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoskarBakalare.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DoskarBakalare.Zapis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hodnota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCloveka")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vaha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Znamky");
                });
#pragma warning restore 612, 618
        }
    }
}
